// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "rebalancerapp-20181001213852--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://rebalancerapp-20181001213852--hostingbucket.s3-website.us-east-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-2:d795bbda-99d5-4985-a01c-4e6220c9acb4",
    "aws_cognito_region": "us-east-2",
    "aws_mobile_analytics_app_id": "d784c2f459fd44899532a65256004c9f",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "rebalancerapi",
            "endpoint": "https://i063evdjb3.execute-api.us-east-2.amazonaws.com/Prod",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
